language: java
language: android
cache: false

sudo: false
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support
    - android-25
    - sys-img-armeabi-v7a-android-25

jdk: oraclejdk8
os:
  - linux

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk: oraclejdk8
branches:
  except:
    - /^[0-9]/ # Workaround to not to trigger Travis with tags - https://github.com/travis-ci/travis-ci/issues/1532
before_install:
  - printf "bintrayUser=$BINTRAY_USER\nbintrayKey=$BINTRAY_KEY\ngradle.publish.key=$GRADLE_PUBLISH_KEY\ngradle.publish.secret=$GRADLE_PUBLISH_SECRET\n" > gradle.properties
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:
  - |
      if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
        echo "Do not open PRs against master; merge dev into master locally and push instead."
        exit 1
      fi
script:
  - ./gradlew clean :plugin:assemble clean :plugin:check
after_success:
  - |
      if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
        echo "CI on master succeded. Executing release tasks..."
        git fetch --unshallow
        ./gradlew bintrayUpload publishPlugins
        ./plugin/ci/tag_release.sh
      fi
